# Generated by Django 2.0.3 on 2018-04-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('sexe', models.CharField(choices=[('Mr', 'Monsieur'), ('Mme', 'Madame')], max_length=1)),
                ('prefer_transport', models.CharField(choices=[('B', 'Bus'), ('T', 'Tram'), ('Vo', 'Voiture'), ('Ve', 'Vélo')], max_length=2)),
                ('subscriptions', models.CharField(choices=[('B', 'BlablaCar'), ('S', 'SNCF'), ('T', 'TCL')], max_length=1)),
            ],
        ),
    ]
