# Generated by Django 2.0.3 on 2018-04-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20180427_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='name',
            field=models.CharField(blank=True, choices=[('B', 'BlablaCar'), ('S', 'SNCF'), ('T', 'TCL')], max_length=1, unique=True),
        ),
    ]
