# Generated by Django 2.0.3 on 2018-04-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20180427_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sexe',
            field=models.CharField(choices=[('Mr', 'Monsieur'), ('Mme', 'Madame')], max_length=3),
        ),
    ]
