# Generated by Django 2.0.3 on 2018-04-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20180427_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prefer_transport',
            field=models.CharField(choices=[('T', 'transit'), ('D', 'driving'), ('B', 'bicycling')], max_length=2),
        ),
    ]
